"""
Copyright 2018 Austin Walker Milt

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

ABILITY_STATES = {
    '40': 'ability s-4 s-4-0',
    '41': 'ability s-4 s-4-1',
    '42': 'ability s-4 s-4-2',
    '43': 'ability s-4 s-4-3',
    '50': 'ability s-5 s-5-0',
    '51': 'ability s-5 s-5-1',
    '52': 'ability s-5 s-5-2',
    '53': 'ability s-5 s-5-3',
    '54': 'ability s-5 s-5-4',
    '60': 'ability s-6 s-6-0',
    '61': 'ability s-6 s-6-1',
    '62': 'ability s-6 s-6-2',
    '63': 'ability s-6 s-6-3',
    '64': 'ability s-6 s-6-4',
    '65': 'ability s-6 s-6-5',
    'ABADDON': ['003', '002', '001', '000'],
    'ALCHEMIST': ['007', '006', '005', '004', '008'],
    'ANCIENT APPARITION': ['010', '011', '012', '013', '009'],
    'ANTI-MAGE': ['014', '015', '016', '017'],
    'ARC WARDEN': ['018', '019', '021', '020'],
    'AXE': ['025', '024', '023', '022'],
    'BANE': ['030', '027', '026', '029', '028'],
    'BATRIDER': ['032', '033', '031', '034'],
    'BEASTMASTER': ['038', '039', '036', '037', '035'],
    'BLOODSEEKER': ['043', '042', '041', '040'],
    'BOUNTY HUNTER': ['047', '046', '045', '044'],
    'BREWMASTER': ['050', '051', '049', '048'],
    'BRISTLEBACK': ['054', '055', '052', '053'],
    'BROODMOTHER': ['056', '057', '058', '059'],
    'CENTAUR WARRUNNER': ['061', '060', '063', '062'],
    'CHAOS KNIGHT': ['065', '064', '067', '066'],
    'CHEN': ['072', '070', '071', '069', '068'],
    'CLINKZ': ['076', '074', '075', '073'],
    'CLOCKWERK': ['077', '078', '079', '080'],
    'CRYSTAL MAIDEN': ['083', '082', '081', '084'],
    'DARK SEER': ['088', '087', '086', '085'],
    'DAZZLE': ['090', '091', '092', '089'],
    'DEATH PROPHET': ['093', '094', '095', '096'],
    'DISRUPTOR': ['100', '098', '099', '097'],
    'DOOM': ['102', '103', '101', '104'],
    'DRAGON KNIGHT': ['108', '106', '107', '105'],
    'DROW RANGER': ['109', '111', '110', '112'],
    'EARTH SPIRIT': ['120', '121', '122', '115', '114', '117', '116', '113', '119', '118'],
    'EARTHSHAKER': ['120', '121', '122', '115', '114', '117', '116', '113', '119', '118'],
    'ELDER TITAN': ['123', '124', '125', '126', '127'],
    'EMBER SPIRIT': ['128', '129', '132', '131', '130'],
    'ENCHANTRESS': ['133', '136', '135', '134'],
    'ENIGMA': ['140', '137', '139', '138'],
    'FACELESS VOID': ['144', '142', '143', '141'],
    'GYROCOPTER': ['146', '147', '145', '148'],
    'HUSKAR': ['149', '151', '150', '152'],
    'INVOKER': ['164', '165', '166', '160', '161', '162', '163', '153', '155', '154', '157', '156', '159', '158'],
    'IO': ['167', '168', '169', '170', '171', '172', '173'],
    'JAKIRO': ['177', '176', '175', '174'],
    'JUGGERNAUT': ['179', '178', '180', '181'],
    'KEEPER OF THE LIGHT': ['182', '183', '186', '187', '184', '185', '188'],
    'KUNKKA': ['191', '190', '193', '192', '189'],
    'LEGION COMMANDER': ['195', '194', '197', '196'],
    'LESHRAC': ['199', '198', '201', '200'],
    'LICH': ['203', '202', '205', '204'],
    'LIFESTEALER': ['210', '211', '209', '208', '207', '206'],
    'LINA': ['214', '215', '212', '213'],
    'LION': ['216', '217', '219', '218'],
    'LONE DRUID': ['225', '224', '223', '222', '221', '220'],
    'LUNA': ['229', '228', '227', '226'],
    'LYCAN': ['230', '231', '232', '233'],
    'MAGNUS': ['234', '235', '236', '237'],
    'MEDUSA': ['238', '239', '241', '240'],
    'MEEPO': ['243', '242', '245', '244'],
    'MIRANA': ['249', '248', '247', '246'],
    'MORPHLING': ['252', '250', '251', '256', '254', '255', '253'],
    'NAGA SIREN': ['258', '261', '260', '259', '257'],
    'NATURES PROPHET': ['262', '263', '264', '265'],
    'NECROPHOS': ['267', '266', '269', '268'],
    'NIGHT STALKER': ['270', '271', '272', '273'],
    'NYX ASSASSIN': ['274', '275', '276', '277', '278', '279'],
    'OGRE MAGI': ['281', '280', '283', '282', '284'],
    'OMNIKNIGHT': ['288', '285', '287', '286'],
    'ORACLE': ['292', '290', '291', '289'],
    'OUTWORLD DEVOURER': ['293', '294', '295', '296'],
    'PHANTOM ASSASSIN': ['298', '299', '297', '300', '301', '302', '303', '304'],
    'PHANTOM LANCER': ['298', '299', '297', '300', '301', '302', '303', '304'],
    'PHOENIX': ['312', '310', '308', '309', '305', '306', '307', '311'],
    'PUCK': ['317', '313', '314', '316', '315'],
    'PUDGE': ['319', '318', '320', '321'],
    'PUGNA': ['322', '323', '324', '325'],
    'QUEEN OF PAIN': ['326', '327', '328', '329'],
    'RAZOR': ['331', '330', '333', '332'],
    'RIKI': ['335', '334', '337', '336'],
    'RUBICK': ['340', '341', '342', '339', '338'],
    'SAND KING': ['344', '345', '346', '343'],
    'SHADOW DEMON': ['347', '348', '349', '360', '361', '351', '350', '359', '358'],
    'SHADOW FIEND': ['347', '348', '349', '360', '361', '351', '350', '359', '358'],
    'SHADOW SHAMAN': ['347', '348', '349', '360', '361', '351', '350', '359', '358'],
    'SILENCER': ['364', '365', '362', '363'],
    'SKYWRATH MAGE': ['368', '369', '367', '366'],
    'SLARDAR': ['370', '371', '373', '372', '375', '374', '377', '376'],
    'SLARK': ['370', '371', '373', '372', '375', '374', '377', '376'],
    'SNIPER': ['380', '381', '379', '378'],
    'SPECTRE': ['384', '385', '386', '382', '383'],
    'SPIRIT BREAKER': ['387', '389', '390', '388'],
    'STORM SPIRIT': ['391', '393', '392', '394'],
    'SVEN': ['395', '398', '397', '396'],
    'TECHIES': ['404', '403', '402', '401', '400', '399'],
    'TEMPLAR ASSASSIN': ['407', '406', '409', '408', '405'],
    'TERRORBLADE': ['410', '411', '412', '413'],
    'TIDEHUNTER': ['414', '415', '416', '417'],
    'TIMBERSAW': ['418', '419', '420', '421', '422', '423', '424'],
    'TINKER': ['428', '432', '431', '429', '425', '427', '426', '430'],
    'TINY': ['428', '432', '431', '429', '425', '427', '426', '430'],
    'TREANT PROTECTOR': ['436', '437', '434', '435', '433'],
    'TROLL WARLORD': ['442', '441', '440', '438', '439'],
    'TUSK': ['448', '443', '447', '446', '445', '444'],
    'UNDERLORD': ['454', '455', '456', '457'],
    'UNDYING': ['454', '455', '456', '457'],
    'URSA': ['461', '460', '458', '459'],
    'VENGEFUL SPIRIT': ['469', '468', '465', '464', '467', '466', '463', '462'],
    'VENOMANCER': ['469', '468', '465', '464', '467', '466', '463', '462'],
    'VIPER': ['473', '472', '470', '471'],
    'VISAGE': ['476', '477', '474', '475'],
    'WARLOCK': ['481', '480', '479', '478'],
    'WEAVER': ['485', '484', '483', '482'],
    'WINDRANGER': ['493', '490', '491', '492', '489', '488', '487', '486'],
    'WINTER WYVERN': ['493', '490', '491', '492', '489', '488', '487', '486'],
    'WITCH DOCTOR': ['497', '494', '495', '496'],
    'WRAITH KING': ['498', '499', '500', '501'],
    'ZEUS': ['502', '503', '504', '505'],
    '000': ['ABADDON', 'abaddon_death_coil', 'abaddon_aphotic_shield', 'abaddon_frostmourne', 'abaddon_borrowed_time'],
    '001': ['ALCHEMIST', 'alchemist_acid_spray', 'alchemist_unstable_concoction', 'alchemist_goblins_greed', 'alchemist_chemical_rage'],
    '002': ['ALCHEMIST', 'alchemist_acid_spray', 'alchemist_unstable_concoction_throw', 'alchemist_goblins_greed', 'alchemist_chemical_rage'],
    '000': ['ANCIENT APPARITION', 'ancient_apparition_cold_feet', 'ancient_apparition_ice_vortex', 'ancient_apparition_chilling_touch', 'ancient_apparition_ice_blast'],
    '000': ['ANCIENT APPARITION', 'ancient_apparition_cold_feet', 'ancient_apparition_ice_vortex', 'ancient_apparition_chilling_touch', 'ancient_apparition_ice_blast_release'],
    '000': ['ANTI-MAGE', 'antimage_mana_break', 'antimage_blink', 'antimage_spell_shield', 'antimage_mana_void'],
    '000': ['ARC WARDEN', 'arc_warden_flux', 'arc_warden_magnetic_field', 'arc_warden_spark_wraith', 'arc_warden_tempest_double'],
    '000': ['AXE', 'axe_berserkers_call', 'axe_battle_hunger', 'axe_counter_helix', 'axe_culling_blade'],
    '000': ['BANE', 'bane_enfeeble', 'bane_brain_sap', 'bane_nightmare', 'bane_fiends_grip'],
    '000': ['BANE', 'bane_enfeeble', 'bane_brain_sap', 'bane_nightmare_end', 'bane_fiends_grip'],
    '000': ['BATRIDER', 'batrider_sticky_napalm', 'batrider_flamebreak', 'batrider_firefly', 'batrider_flaming_lasso'],
    '000': ['BEASTMASTER', 'beastmaster_wild_axes', 'beastmaster_call_of_the_wild', 'beastmaster_call_of_the_wild', 'beastmaster_inner_beast', 'beastmaster_primal_roar'],
    '000': ['BLOODSEEKER', 'bloodseeker_bloodrage', 'bloodseeker_blood_bath', 'bloodseeker_thirst', 'bloodseeker_rupture'],
    '000': ['BOUNTY HUNTER', 'bounty_hunter_shuriken_toss', 'bounty_hunter_jinada', 'bounty_hunter_wind_walk', 'bounty_hunter_track'],
    '000': ['BREWMASTER', 'brewmaster_thunder_clap', 'brewmaster_drunken_haze', 'brewmaster_drunken_brawler', 'brewmaster_primal_split'],
    '000': ['BRISTLEBACK', 'bristleback_viscous_nasal_goo', 'bristleback_quill_spray', 'bristleback_bristleback', 'bristleback_warpath'],
    '000': ['BROODMOTHER', 'broodmother_spawn_spiderlings', 'broodmother_spin_web', 'broodmother_incapacitating_bite', 'broodmother_insatiable_hunger'],
    '000': ['CENTAUR WARRUNNER', 'centaur_hoof_stomp', 'centaur_double_edge', 'centaur_return', 'centaur_stampede'],
    '000': ['CHAOS KNIGHT', 'chaos_knight_chaos_bolt', 'chaos_knight_reality_rift', 'chaos_knight_chaos_strike', 'chaos_knight_phantasm'],
    '000': ['CHEN', 'chen_penitence', 'chen_test_of_faith', 'chen_test_of_faith_teleport', 'chen_holy_persuasion', 'chen_hand_of_god'],
    '000': ['CLINKZ', 'clinkz_strafe', 'clinkz_searing_arrows', 'clinkz_wind_walk', 'clinkz_death_pact'],
    '000': ['CLOCKWERK', 'rattletrap_battery_assault', 'rattletrap_power_cogs', 'rattletrap_rocket_flare', 'rattletrap_hookshot'],
    '000': ['CRYSTAL MAIDEN', 'crystal_maiden_crystal_nova', 'crystal_maiden_frostbite', 'crystal_maiden_brilliance_aura', 'crystal_maiden_freezing_field'],
    '000': ['DARK SEER', 'dark_seer_vacuum', 'dark_seer_ion_shell', 'dark_seer_surge', 'dark_seer_wall_of_replica'],
    '000': ['DAZZLE', 'dazzle_poison_touch', 'dazzle_shallow_grave', 'dazzle_shadow_wave', 'dazzle_weave'],
    '000': ['DEATH PROPHET', 'death_prophet_carrion_swarm', 'death_prophet_silence', 'death_prophet_spirit_siphon', 'death_prophet_exorcism'],
    '000': ['DISRUPTOR', 'disruptor_thunder_strike', 'disruptor_glimpse', 'disruptor_kinetic_field', 'disruptor_static_storm'],
    '000': ['DOOM', 'doom_bringer_devour', 'doom_bringer_scorched_earth', 'doom_bringer_infernal_blade', '', '', 'doom_bringer_doom'],
    '000': ['DRAGON KNIGHT', 'dragon_knight_breathe_fire', 'dragon_knight_dragon_tail', 'dragon_knight_dragon_blood', 'dragon_knight_elder_dragon_form'],
    '000': ['DROW RANGER', 'drow_ranger_frost_arrows', 'drow_ranger_wave_of_silence', 'drow_ranger_trueshot', 'drow_ranger_marksmanship'],
    '000': ['EARTH SPIRIT', 'earth_spirit_boulder_smash', 'earth_spirit_rolling_boulder', 'earth_spirit_geomagnetic_grip', 'earth_spirit_stone_caller', 'earth_spirit_magnetize'],
    '000': ['EARTH SPIRIT', 'earth_spirit_boulder_smash', 'earth_spirit_rolling_boulder', 'earth_spirit_geomagnetic_grip', 'earth_spirit_stone_caller', 'earth_spirit_petrify', 'earth_spirit_magnetize'],
    '000': ['EARTHSHAKER', 'earthshaker_fissure', 'earthshaker_enchant_totem', 'earthshaker_aftershock', 'earthshaker_echo_slam'],
    '000': ['ELDER TITAN', 'elder_titan_echo_stomp', 'elder_titan_ancestral_spirit', 'elder_titan_natural_order', 'elder_titan_earth_splitter'],
    '000': ['ELDER TITAN', 'elder_titan_echo_stomp', 'elder_titan_return_spirit', 'elder_titan_natural_order', 'elder_titan_earth_splitter'],
    '000': ['EMBER SPIRIT', 'ember_spirit_searing_chains', 'ember_spirit_sleight_of_fist', 'ember_spirit_flame_guard', 'ember_spirit_activate_fire_remnant', 'ember_spirit_fire_remnant'],
    '000': ['ENCHANTRESS', 'enchantress_untouchable', 'enchantress_enchant', 'enchantress_natures_attendants', 'enchantress_impetus'],
    '000': ['ENIGMA', 'enigma_malefice', 'enigma_demonic_conversion', 'enigma_midnight_pulse', 'enigma_black_hole'],
    '000': ['FACELESS VOID', 'faceless_void_time_walk', 'faceless_void_time_dilation', 'faceless_void_time_lock', 'faceless_void_chronosphere'],
    '000': ['GYROCOPTER', 'gyrocopter_rocket_barrage', 'gyrocopter_homing_missile', 'gyrocopter_flak_cannon', 'gyrocopter_call_down'],
    '000': ['HUSKAR', 'huskar_inner_vitality', 'huskar_burning_spear', 'huskar_berserkers_blood', 'huskar_life_break'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_cold_snap', 'invoker_ghost_walk', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_cold_snap', 'invoker_tornado', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_cold_snap', 'invoker_emp', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_cold_snap', 'invoker_alacrity', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_cold_snap', 'invoker_chaos_meteor', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_cold_snap', 'invoker_sun_strike', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_cold_snap', 'invoker_forge_spirit', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_cold_snap', 'invoker_ice_wall', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_cold_snap', 'invoker_deafening_blast', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ghost_walk', 'invoker_cold_snap', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ghost_walk', 'invoker_tornado', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ghost_walk', 'invoker_emp', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ghost_walk', 'invoker_alacrity', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ghost_walk', 'invoker_chaos_meteor', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ghost_walk', 'invoker_sun_strike', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ghost_walk', 'invoker_forge_spirit', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ghost_walk', 'invoker_ice_wall', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ghost_walk', 'invoker_deafening_blast', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_tornado', 'invoker_cold_snap', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_tornado', 'invoker_ghost_walk', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_tornado', 'invoker_emp', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_tornado', 'invoker_alacrity', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_tornado', 'invoker_chaos_meteor', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_tornado', 'invoker_sun_strike', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_tornado', 'invoker_forge_spirit', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_tornado', 'invoker_ice_wall', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_tornado', 'invoker_deafening_blast', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_emp', 'invoker_cold_snap', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_emp', 'invoker_ghost_walk', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_emp', 'invoker_tornado', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_emp', 'invoker_alacrity', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_emp', 'invoker_chaos_meteor', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_emp', 'invoker_sun_strike', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_emp', 'invoker_forge_spirit', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_emp', 'invoker_ice_wall', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_emp', 'invoker_deafening_blast', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_alacrity', 'invoker_cold_snap', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_alacrity', 'invoker_ghost_walk', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_alacrity', 'invoker_tornado', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_alacrity', 'invoker_emp', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_alacrity', 'invoker_chaos_meteor', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_alacrity', 'invoker_sun_strike', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_alacrity', 'invoker_forge_spirit', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_alacrity', 'invoker_ice_wall', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_alacrity', 'invoker_deafening_blast', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_chaos_meteor', 'invoker_cold_snap', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_chaos_meteor', 'invoker_ghost_walk', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_chaos_meteor', 'invoker_tornado', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_chaos_meteor', 'invoker_emp', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_chaos_meteor', 'invoker_alacrity', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_chaos_meteor', 'invoker_sun_strike', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_chaos_meteor', 'invoker_forge_spirit', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_chaos_meteor', 'invoker_ice_wall', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_chaos_meteor', 'invoker_deafening_blast', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_sun_strike', 'invoker_cold_snap', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_sun_strike', 'invoker_ghost_walk', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_sun_strike', 'invoker_tornado', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_sun_strike', 'invoker_emp', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_sun_strike', 'invoker_alacrity', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_sun_strike', 'invoker_chaos_meteor', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_sun_strike', 'invoker_forge_spirit', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_sun_strike', 'invoker_ice_wall', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_sun_strike', 'invoker_deafening_blast', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_forge_spirit', 'invoker_cold_snap', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_forge_spirit', 'invoker_ghost_walk', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_forge_spirit', 'invoker_tornado', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_forge_spirit', 'invoker_emp', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_forge_spirit', 'invoker_alacrity', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_forge_spirit', 'invoker_chaos_meteor', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_forge_spirit', 'invoker_sun_strike', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_forge_spirit', 'invoker_ice_wall', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_forge_spirit', 'invoker_deafening_blast', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ice_wall', 'invoker_cold_snap', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ice_wall', 'invoker_ghost_walk', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ice_wall', 'invoker_tornado', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ice_wall', 'invoker_emp', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ice_wall', 'invoker_alacrity', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ice_wall', 'invoker_chaos_meteor', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ice_wall', 'invoker_sun_strike', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ice_wall', 'invoker_forge_spirit', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_ice_wall', 'invoker_deafening_blast', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_deafening_blast', 'invoker_cold_snap', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_deafening_blast', 'invoker_ghost_walk', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_deafening_blast', 'invoker_tornado', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_deafening_blast', 'invoker_emp', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_deafening_blast', 'invoker_alacrity', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_deafening_blast', 'invoker_chaos_meteor', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_deafening_blast', 'invoker_sun_strike', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_deafening_blast', 'invoker_forge_spirit', 'invoker_invoke'],
    '000': ['INVOKER', 'invoker_quas', 'invoker_wex', 'invoker_exort', 'invoker_deafening_blast', 'invoker_ice_wall', 'invoker_invoke'],
    '000': ['IO', 'wisp_tether', 'wisp_spirits', 'wisp_overcharge', 'wisp_spirits_in', 'wisp_spirits_out', 'wisp_relocate'],
    '000': ['IO', 'wisp_tether_break', 'wisp_spirits', 'wisp_overcharge', 'wisp_spirits_in', 'wisp_spirits_out', 'wisp_relocate'],
    '000': ['JAKIRO', 'jakiro_dual_breath', 'jakiro_ice_path', 'jakiro_liquid_fire', 'jakiro_macropyre'],
    '000': ['JUGGERNAUT', 'juggernaut_blade_fury', 'juggernaut_healing_ward', 'juggernaut_blade_dance', 'juggernaut_omni_slash'],
    '000': ['KEEPER OF THE LIGHT', 'keeper_of_the_light_illuminate', 'keeper_of_the_light_mana_leak', 'keeper_of_the_light_chakra_magic', 'keeper_of_the_light_recall', 'keeper_of_the_light_blinding_light', 'keeper_of_the_light_spirit_form'],
    '000': ['KEEPER OF THE LIGHT', 'keeper_of_the_light_illuminate_end', 'keeper_of_the_light_mana_leak', 'keeper_of_the_light_chakra_magic', 'keeper_of_the_light_recall', 'keeper_of_the_light_blinding_light', 'keeper_of_the_light_spirit_form'],
    ######### STOPPED HERE ########
    ## TO DO
    ##  1. Finish comparing to ability_class.js for order/states
    ##  2. Replace hero name key entries with numbers for their states below, e.g. Abaddon: [000] or Earth spirit: [000, 000]
    ##  3. When doing library building, process this as a dict in python to determine how to prompt user for image classification:
    ##      a. Prompt user for hero name.
    ##      b. Look up that hero in this dict.
    ##      c. If the hero has only one state, we dont need to prompt the user for ability names and can finish the frame (i.e. go back to 3.a. for next frame)
    ##      d. If the hero can have more than one number of ability slots, ask user which it is (e.g. 4 or 5).
    ##      e. Store an image for the first ability slot that doesnt change for the hero (to later determine which state the hero is in).
    ##      f. If the hero has only one state with that number of ability slots, you're done and can finish the frame.
    ##      g. For every ability slot that can take on multiple abilities, prompt the user to identify the ability from the possible list. The list is:
    ##
    ##          for every state in ABILITY_STATES[hero]:
    ##              if len(ABILITY_STATES[state][1:]) == (3.d):
    ##                  create a list of sets containing all possible abilities in the i-th slot
    ##
    ##  4. When doing image matching, use this as a dict in python to determine abilities
    ##      a. Do image matching for the hero name, as you already do
    ##      b. Look up the hero name in this dict to get a list of possible states
    ##      c. If the hero has only one state, you're done
    ##      d. If the hero has states with different numbers of ability slots, programmatically determine which number of slots it is (by comparing from 3.e)
    ##      e. Once you've determined 4.d, if the hero has more than one state with this number of slots, programmatically determine which ability is in the unknown slot
    ##
    ##  5. Need to update tooltip_manager.js
    ###############################
    '000': ['KUNKKA', 'kunkka_torrent', 'kunkka_tidebringer', 'kunkka_x_marks_the_spot', 'kunkka_return', 'kunkka_ghostship'],
    '000': ['LEGION COMMANDER', 'legion_commander_overwhelming_odds', 'legion_commander_press_the_attack', 'legion_commander_moment_of_courage', 'legion_commander_duel'],
    '000': ['LESHRAC', 'leshrac_split_earth', 'leshrac_diabolic_edict', 'leshrac_lightning_storm', 'leshrac_pulse_nova'],
    '000': ['LICH', 'lich_frost_nova', 'lich_frost_armor', 'lich_dark_ritual', 'lich_chain_frost'],
    '000': ['LIFESTEALER', 'life_stealer_rage', 'life_stealer_feast', 'life_stealer_open_wounds', 'life_stealer_assimilate', 'life_stealer_assimilate_eject', 'life_stealer_infest'],
    '000': ['LINA', 'lina_dragon_slave', 'lina_light_strike_array', 'lina_fiery_soul', 'lina_laguna_blade'],
    '000': ['LION', 'lion_impale', 'lion_voodoo', 'lion_mana_drain', 'lion_finger_of_death'],
    '000': ['LONE DRUID', 'lone_druid_spirit_bear', 'lone_druid_rabid', 'lone_druid_savage_roar', 'lone_druid_true_form_battle_cry', 'lone_druid_true_form', 'lone_druid_true_form_druid'],
    '000': ['LUNA', 'luna_lucent_beam', 'luna_moon_glaive', 'luna_lunar_blessing', 'luna_eclipse'],
    '000': ['LYCAN', 'lycan_summon_wolves', 'lycan_howl', 'lycan_feral_impulse', 'lycan_shapeshift'],
    '000': ['MAGNUS', 'magnataur_shockwave', 'magnataur_empower', 'magnataur_skewer', 'magnataur_reverse_polarity'],
    '000': ['MEDUSA', 'medusa_split_shot', 'medusa_mystic_snake', 'medusa_mana_shield', 'medusa_stone_gaze'],
    '000': ['MEEPO', 'meepo_earthbind', 'meepo_poof', 'meepo_geostrike', 'meepo_divided_we_stand'],
    '000': ['MIRANA', 'mirana_starfall', 'mirana_arrow', 'mirana_leap', 'mirana_invis'],
    '000': ['MORPHLING', 'morphling_waveform', 'morphling_adaptive_strike', 'morphling_morph_agi', 'morphling_morph_str', 'morphling_hybrid', 'morphling_replicate', 'morphling_morph_replicate'],
    '000': ['NAGA SIREN', 'naga_siren_mirror_image', 'naga_siren_ensnare', 'naga_siren_rip_tide', 'naga_siren_song_of_the_siren', 'naga_siren_song_of_the_siren_cancel'],
    '000': ['NATURES PROPHET', 'furion_sprout', 'furion_teleportation', 'furion_force_of_nature', 'furion_wrath_of_nature'],
    '000': ['NECROPHOS', 'necrolyte_death_pulse', 'necrolyte_heartstopper_aura', 'necrolyte_sadist', 'necrolyte_reapers_scythe'],
    '000': ['NIGHT STALKER', 'night_stalker_void', 'night_stalker_crippling_fear', 'night_stalker_hunter_in_the_night', 'night_stalker_darkness'],
    '000': ['NYX ASSASSIN', 'nyx_assassin_impale', 'nyx_assassin_mana_burn', 'nyx_assassin_spiked_carapace', 'nyx_assassin_burrow', 'nyx_assassin_unburrow', 'nyx_assassin_vendetta'],
    '000': ['OGRE MAGI', 'ogre_magi_fireblast', 'ogre_magi_ignite', 'ogre_magi_bloodlust', 'ogre_magi_unrefined_fireblast', 'ogre_magi_multicast'],
    '000': ['OMNIKNIGHT', 'omniknight_purification', 'omniknight_repel', 'omniknight_degen_aura', 'omniknight_guardian_angel'],
    '000': ['ORACLE', 'oracle_fortunes_end', 'oracle_fates_edict', 'oracle_purifying_flames', 'oracle_false_promise'],
    '000': ['OUTWORLD DEVOURER', 'obsidian_destroyer_arcane_orb', 'obsidian_destroyer_astral_imprisonment', 'obsidian_destroyer_essence_aura', 'obsidian_destroyer_sanity_eclipse'],
    '000': ['PHANTOM ASSASSIN', 'phantom_assassin_stifling_dagger', 'phantom_assassin_phantom_strike', 'phantom_assassin_blur', 'phantom_assassin_coup_de_grace', 'phantom_lancer_spirit_lance', 'phantom_lancer_doppelwalk', 'phantom_lancer_phantom_edge', 'phantom_lancer_juxtapose'],
    '000': ['PHANTOM LANCER', 'phantom_assassin_stifling_dagger', 'phantom_assassin_phantom_strike', 'phantom_assassin_blur', 'phantom_assassin_coup_de_grace', 'phantom_lancer_spirit_lance', 'phantom_lancer_doppelwalk', 'phantom_lancer_phantom_edge', 'phantom_lancer_juxtapose'],
    '000': ['PHOENIX', 'phoenix_icarus_dive', 'phoenix_icarus_dive_stop', 'phoenix_fire_spirits', 'phoenix_launch_fire_spirit', 'phoenix_sun_ray', 'phoenix_sun_ray_stop', 'phoenix_sun_ray_toggle_move', 'phoenix_supernova'],
    '000': ['PUCK', 'puck_illusory_orb', 'puck_waning_rift', 'puck_phase_shift', 'puck_ethereal_jaunt', 'puck_dream_coil'],
    '000': ['PUDGE', 'pudge_meat_hook', 'pudge_rot', 'pudge_flesh_heap', 'pudge_dismember'],
    '000': ['PUGNA', 'pugna_nether_blast', 'pugna_decrepify', 'pugna_nether_ward', 'pugna_life_drain'],
    '000': ['QUEEN OF PAIN', 'queenofpain_shadow_strike', 'queenofpain_blink', 'queenofpain_scream_of_pain', 'queenofpain_sonic_wave'],
    '000': ['RAZOR', 'razor_plasma_field', 'razor_static_link', 'razor_unstable_current', 'razor_eye_of_the_storm'],
    '000': ['RIKI', 'riki_smoke_screen', 'riki_blink_strike', 'riki_permanent_invisibility', 'riki_tricks_of_the_trade'],
    '000': ['RUBICK', 'rubick_telekinesis', 'rubick_telekinesis_land', 'rubick_fade_bolt', 'rubick_null_field', 'rubick_spell_steal'],
    '000': ['SAND KING', 'sandking_burrowstrike', 'sandking_sand_storm', 'sandking_caustic_finale', 'sandking_epicenter'],
    '000': ['SHADOW DEMON', 'shadow_demon_disruption', 'shadow_demon_soul_catcher', 'shadow_demon_shadow_poison', 'shadow_demon_shadow_poison_release', 'shadow_demon_demonic_purge', 'shadow_shaman_ether_shock', 'shadow_shaman_voodoo', 'shadow_shaman_shackles', 'shadow_shaman_mass_serpent_ward'],
    '000': ['SHADOW FIEND', 'shadow_demon_disruption', 'shadow_demon_soul_catcher', 'shadow_demon_shadow_poison', 'shadow_demon_shadow_poison_release', 'shadow_demon_demonic_purge', 'shadow_shaman_ether_shock', 'shadow_shaman_voodoo', 'shadow_shaman_shackles', 'shadow_shaman_mass_serpent_ward'],
    '000': ['SHADOW SHAMAN', 'shadow_demon_disruption', 'shadow_demon_soul_catcher', 'shadow_demon_shadow_poison', 'shadow_demon_shadow_poison_release', 'shadow_demon_demonic_purge', 'shadow_shaman_ether_shock', 'shadow_shaman_voodoo', 'shadow_shaman_shackles', 'shadow_shaman_mass_serpent_ward'],
    '000': ['SILENCER', 'silencer_curse_of_the_silent', 'silencer_glaives_of_wisdom', 'silencer_last_word', 'silencer_global_silence'],
    '000': ['SKYWRATH MAGE', 'skywrath_mage_arcane_bolt', 'skywrath_mage_concussive_shot', 'skywrath_mage_ancient_seal', 'skywrath_mage_mystic_flare'],
    '000': ['SLARDAR', 'slardar_sprint', 'slardar_slithereen_crush', 'slardar_bash', 'slardar_amplify_damage', 'slark_dark_pact', 'slark_pounce', 'slark_essence_shift', 'slark_shadow_dance'],
    '000': ['SLARK', 'slardar_sprint', 'slardar_slithereen_crush', 'slardar_bash', 'slardar_amplify_damage', 'slark_dark_pact', 'slark_pounce', 'slark_essence_shift', 'slark_shadow_dance'],
    '000': ['SNIPER', 'sniper_shrapnel', 'sniper_headshot', 'sniper_take_aim', 'sniper_assassinate'],
    '000': ['SPECTRE', 'spectre_spectral_dagger', 'spectre_desolate', 'spectre_dispersion', 'spectre_reality', 'spectre_haunt'],
    '000': ['SPIRIT BREAKER', 'spirit_breaker_charge_of_darkness', 'spirit_breaker_empowering_haste', 'spirit_breaker_greater_bash', 'spirit_breaker_nether_strike'],
    '000': ['STORM SPIRIT', 'storm_spirit_static_remnant', 'storm_spirit_electric_vortex', 'storm_spirit_overload', 'storm_spirit_ball_lightning'],
    '000': ['SVEN', 'sven_storm_bolt', 'sven_great_cleave', 'sven_warcry', 'sven_gods_strength'],
    '000': ['TECHIES', 'techies_land_mines', 'techies_stasis_trap', 'techies_suicide', 'techies_focused_detonate', 'techies_minefield_sign', 'techies_remote_mines'],
    '000': ['TEMPLAR ASSASSIN', 'templar_assassin_refraction', 'templar_assassin_meld', 'templar_assassin_psi_blades', 'templar_assassin_trap', 'templar_assassin_psionic_trap'],
    '000': ['TERRORBLADE', 'terrorblade_reflection', 'terrorblade_conjure_image', 'terrorblade_metamorphosis', 'terrorblade_sunder'],
    '000': ['TIDEHUNTER', 'tidehunter_gush', 'tidehunter_kraken_shell', 'tidehunter_anchor_smash', 'tidehunter_ravage'],
    '000': ['TIMBERSAW', 'shredder_whirling_death', 'shredder_timber_chain', 'shredder_reactive_armor', 'shredder_chakram_2', 'shredder_return_chakram_2', 'shredder_chakram', 'shredder_return_chakram'],
    '000': ['TINKER', 'tinker_laser', 'tinker_heat_seeking_missile', 'tinker_march_of_the_machines', 'tinker_rearm', 'tiny_avalanche', 'tiny_toss', 'tiny_craggy_exterior', 'tiny_grow'],
    '000': ['TINY', 'tinker_laser', 'tinker_heat_seeking_missile', 'tinker_march_of_the_machines', 'tinker_rearm', 'tiny_avalanche', 'tiny_toss', 'tiny_craggy_exterior', 'tiny_grow'],
    '000': ['TREANT PROTECTOR', 'treant_natures_guise', 'treant_leech_seed', 'treant_living_armor', 'treant_eyes_in_the_forest', 'treant_overgrowth'],
    '000': ['TROLL WARLORD', 'troll_warlord_berserkers_rage', 'troll_warlord_whirling_axes_ranged', 'troll_warlord_whirling_axes_melee', 'troll_warlord_fervor', 'troll_warlord_battle_trance'],
    '000': ['TUSK', 'tusk_ice_shards', 'tusk_snowball', 'tusk_launch_snowball', 'tusk_frozen_sigil', 'tusk_walrus_kick', 'tusk_walrus_punch'],
    '000': ['UNDERLORD', 'undying_decay', 'undying_soul_rip', 'undying_tombstone', 'undying_flesh_golem'],
    '000': ['UNDYING', 'undying_decay', 'undying_soul_rip', 'undying_tombstone', 'undying_flesh_golem'],
    '000': ['URSA', 'ursa_earthshock', 'ursa_overpower', 'ursa_fury_swipes', 'ursa_enrage'],
    '000': ['VENGEFUL SPIRIT', 'vengefulspirit_magic_missile', 'vengefulspirit_wave_of_terror', 'vengefulspirit_command_aura', 'vengefulspirit_nether_swap', 'venomancer_venomous_gale', 'venomancer_poison_sting', 'venomancer_plague_ward', 'venomancer_poison_nova'],
    '000': ['VENOMANCER', 'vengefulspirit_magic_missile', 'vengefulspirit_wave_of_terror', 'vengefulspirit_command_aura', 'vengefulspirit_nether_swap', 'venomancer_venomous_gale', 'venomancer_poison_sting', 'venomancer_plague_ward', 'venomancer_poison_nova'],
    '000': ['VIPER', 'viper_poison_attack', 'viper_nethertoxin', 'viper_corrosive_skin', 'viper_viper_strike'],
    '000': ['VISAGE', 'visage_grave_chill', 'visage_soul_assumption', 'visage_gravekeepers_cloak', 'visage_summon_familiars'],
    '000': ['WARLOCK', 'warlock_fatal_bonds', 'warlock_shadow_word', 'warlock_upheaval', 'warlock_rain_of_chaos'],
    '000': ['WEAVER', 'weaver_the_swarm', 'weaver_shukuchi', 'weaver_geminate_attack', 'weaver_time_lapse'],
    '000': ['WINDRANGER', 'windrunner_shackleshot', 'windrunner_powershot', 'windrunner_windrun', 'windrunner_focusfire', 'winter_wyvern_arctic_burn', 'winter_wyvern_splinter_blast', 'winter_wyvern_cold_embrace', 'winter_wyvern_winters_curse'],
    '000': ['WINTER WYVERN', 'windrunner_shackleshot', 'windrunner_powershot', 'windrunner_windrun', 'windrunner_focusfire', 'winter_wyvern_arctic_burn', 'winter_wyvern_splinter_blast', 'winter_wyvern_cold_embrace', 'winter_wyvern_winters_curse'],
    '000': ['WITCH DOCTOR', 'witch_doctor_paralyzing_cask', 'witch_doctor_voodoo_restoration', 'witch_doctor_maledict', 'witch_doctor_death_ward'],
    '000': ['WRAITH KING', 'skeleton_king_hellfire_blast', 'skeleton_king_vampiric_aura', 'skeleton_king_mortal_strike', 'skeleton_king_reincarnation'],
    '000': ['ZEUS', 'zuus_arc_lightning', 'zuus_lightning_bolt', 'zuus_static_field', 'zuus_thundergods_wrath'],

}