"""
Copyright 2018 Austin Walker Milt

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

names = [
    'ABADDON',
	'ALCHEMIST', 
	'ANCIENT APPARITION', 
	'ANTI-MAGE', 
	'ARC WARDEN', 
	'AXE', 
	'BANE', 
	'BATRIDER', 
	'BEASTMASTER', 
	'BLOODSEEKER', 
	'BOUNTY HUNTER', 
	'BREWMASTER', 
	'BRISTLEBACK', 
	'BROODMOTHER', 
	'CENTAUR WARRUNNER', 
	'CHAOS KNIGHT', 
	'CHEN', 
	'CLINKZ', 
	'CLOCKWERK', 
	'CRYSTAL MAIDEN', 
	'DARK SEER', 
	'DAZZLE', 
	'DEATH PROPHET', 
	'DISRUPTOR', 
	'DOOM', 
	'DRAGON KNIGHT', 
	'DROW RANGER', 
	'EARTH SPIRIT', 
	'EARTHSHAKER', 
	'ELDER TITAN', 
	'EMBER SPIRIT', 
	'ENCHANTRESS', 
	'ENIGMA', 
	'FACELESS VOID', 
	'GYROCOPTER', 
	'HUSKAR', 
	'INVOKER', 
	'IO', 
	'JAKIRO', 
	'JUGGERNAUT', 
	'KEEPER OF THE LIGHT', 
	'KUNKKA', 
	'LEGION COMMANDER', 
	'LESHRAC', 
	'LICH', 
	'LIFESTEALER', 
	'LINA', 
	'LION', 
	'LONE DRUID', 
	'LUNA', 
	'LYCAN', 
	'MAGNUS', 
	'MEDUSA', 
	'MEEPO', 
	'MIRANA', 
	'MORPHLING', 
	'NAGA SIREN', 
	'NATURES PROPHET', 
	'NECROPHOS', 
	'NIGHT STALKER', 
	'NYX ASSASSIN', 
	'OGRE MAGI', 
	'OMNIKNIGHT', 
	'ORACLE', 
	'OUTWORLD DEVOURER', 
	'PHANTOM ASSASSIN', 
	'PHANTOM LANCER', 
	'PHOENIX', 
	'PUCK', 
	'PUDGE', 
	'PUGNA', 
	'QUEEN OF PAIN', 
	'RAZOR', 
	'RIKI', 
	'RUBICK', 
	'SAND KING', 
	'SHADOW DEMON', 
	'SHADOW FIEND', 
	'SHADOW SHAMAN', 
	'SILENCER', 
	'SKYWRATH MAGE', 
	'SLARDAR', 
	'SLARK', 
	'SNIPER', 
	'SPECTRE', 
	'SPIRIT BREAKER', 
	'STORM SPIRIT', 
	'SVEN', 
	'TECHIES', 
	'TEMPLAR ASSASSIN', 
	'TERRORBLADE', 
	'TIDEHUNTER', 
	'TIMBERSAW', 
	'TINKER', 
	'TINY', 
	'TREANT PROTECTOR', 
	'TROLL WARLORD', 
	'TUSK', 
	'UNDERLORD', 
	'UNDYING', 
	'URSA', 
	'VENGEFUL SPIRIT', 
	'VENOMANCER', 
	'VIPER', 
	'VISAGE', 
	'WARLOCK', 
	'WEAVER', 
	'WINDRANGER', 
	'WINTER WYVERN', 
	'WITCH DOCTOR', 
	'WRAITH KING', 
	'ZEUS'
]